language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install libgl1-mesa-dev qt59base qt59imageformats qt59svg qt59charts-no-lgpl qt59tools
    - source /opt/qt*/bin/qt*-env.sh

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir install ; find appdir/
  - # FIXME: Once everything is properly merged, the next line should be removed
  - ( mkdir -p ./appdir/usr/share/applications/ ; cp native/stacer.desktop ./appdir/usr/share/applications/ )
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Stacer*.AppImage https://transfer.sh/Stacer-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - # FIXME: use uploadtool to upload to GitHub Releases
